config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'pages#home'
  get '/albums/new', to: 'pages#new'
  
  post '/albums/create', to: 'pages#create'

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @albums = Album.all
  end
  def new
  end
  def create
    # rails g model Album title:string artist:string year:integer
    Album.create(
      :title=> params[:title],
      :artist => params[:artist], 
      :year => params[:year])
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fa16Lecture3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/create.html.erb
<%= @title %>
<%= @artist %>

app/views/pages/home.html.erb
<h1>Welcome</h1>

<% if 1 == 1 %>
  <h3><%= "1 equals 1." %></h3>
<% end %>

<%= link_to "Make a new form", albums_new_path %>

<table>
  <tr>
    <td>title</td>
    <td>artist</td>
    <td>year</td>
  </tr>
  <% @albums.each do |album| %>
    <tr>
      <td><%= album.title%></td>
      <td><%= album.artist%></td>
      <td><%= album.year%></td>
    </tr>
  <% end %>
</table>

app/views/pages/new.html.erb
<%= form_tag albums_create_path do %>
  <%= label_tag(:year, "year: ") %>
  <%= text_field_tag(:year) %>

  <%= label_tag(:title, "title: ") %>
  <%= text_field_tag(:title) %>

  <%= label_tag(:artist, "artist: ") %>
  <%= text_field_tag(:artist) %>

  <%= submit_tag("Create Album") %>
<% end %>